org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=qlmzombie
mod_name=七零喵僵尸末日生存mod
mod_license=MIT
mod_version=3.0.0.beta.build40
mod_group_id=com.qlm.zombie
mod_authors=SevenZeroMeow Team
mod_description=七零喵僵尸末日生存mod (Kotlin+Java+KubeJS重构版) - 基于开源模组整合的末日生存mod

kotlin_for_forge_version=5.3.0
kubejs_version=2001.6.5-build.16
cloth_config_version=11.1.136-forge
puzzleslib_version=11.1.0
